name: CRM CI

on:
  push:
    branches: ["devops-infra", "main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # BACKEND (у тебя crm-backend!)
      - name: Install backend
        working-directory: ./crm-backend
        run: npm install

      - name: Build backend
        working-directory: ./crm-backend
        run: npm run build || echo "no build script"

      # FRONTEND
      - name: Install frontend
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build